<?php
/**
 * DocumentIssuedFilter
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tsukiro\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Tsukiro\Client\Model;

use \ArrayAccess;
use \Tsukiro\Client\ObjectSerializer;

/**
 * DocumentIssuedFilter Class Doc Comment
 *
 * @category Class
 * @package  Tsukiro\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentIssuedFilter implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DocumentIssuedFilter';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'page' => 'string',
'tipo_dte' => '\Tsukiro\Client\Model\DTEFilter',
'fch_emis' => '\Tsukiro\Client\Model\DTEFilter',
'rut_receptor' => '\Tsukiro\Client\Model\DTEFilter'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'page' => null,
'tipo_dte' => null,
'fch_emis' => null,
'rut_receptor' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'page' => 'page',
'tipo_dte' => 'TipoDTE',
'fch_emis' => 'FchEmis',
'rut_receptor' => 'RUTReceptor'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'page' => 'setPage',
'tipo_dte' => 'setTipoDte',
'fch_emis' => 'setFchEmis',
'rut_receptor' => 'setRutReceptor'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'page' => 'getPage',
'tipo_dte' => 'getTipoDte',
'fch_emis' => 'getFchEmis',
'rut_receptor' => 'getRutReceptor'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['page'] = isset($data['page']) ? $data['page'] : null;
        $this->container['tipo_dte'] = isset($data['tipo_dte']) ? $data['tipo_dte'] : null;
        $this->container['fch_emis'] = isset($data['fch_emis']) ? $data['fch_emis'] : null;
        $this->container['rut_receptor'] = isset($data['rut_receptor']) ? $data['rut_receptor'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets page
     *
     * @return string
     */
    public function getPage()
    {
        return $this->container['page'];
    }

    /**
     * Sets page
     *
     * @param string $page page
     *
     * @return $this
     */
    public function setPage($page)
    {
        $this->container['page'] = $page;

        return $this;
    }

    /**
     * Gets tipo_dte
     *
     * @return \Tsukiro\Client\Model\DTEFilter
     */
    public function getTipoDte()
    {
        return $this->container['tipo_dte'];
    }

    /**
     * Sets tipo_dte
     *
     * @param \Tsukiro\Client\Model\DTEFilter $tipo_dte tipo_dte
     *
     * @return $this
     */
    public function setTipoDte($tipo_dte)
    {
        $this->container['tipo_dte'] = $tipo_dte;

        return $this;
    }

    /**
     * Gets fch_emis
     *
     * @return \Tsukiro\Client\Model\DTEFilter
     */
    public function getFchEmis()
    {
        return $this->container['fch_emis'];
    }

    /**
     * Sets fch_emis
     *
     * @param \Tsukiro\Client\Model\DTEFilter $fch_emis fch_emis
     *
     * @return $this
     */
    public function setFchEmis($fch_emis)
    {
        $this->container['fch_emis'] = $fch_emis;

        return $this;
    }

    /**
     * Gets rut_receptor
     *
     * @return \Tsukiro\Client\Model\DTEFilter
     */
    public function getRutReceptor()
    {
        return $this->container['rut_receptor'];
    }

    /**
     * Sets rut_receptor
     *
     * @param \Tsukiro\Client\Model\DTEFilter $rut_receptor rut_receptor
     *
     * @return $this
     */
    public function setRutReceptor($rut_receptor)
    {
        $this->container['rut_receptor'] = $rut_receptor;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
