<?php
/**
 * DTEReferenciaItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tsukiro\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Tsukiro\Client\Model;

use \ArrayAccess;
use \Tsukiro\Client\ObjectSerializer;

/**
 * DTEReferenciaItem Class Doc Comment
 *
 * @category Class
 * @package  Tsukiro\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DTEReferenciaItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DTEReferenciaItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'fch_ref' => 'string',
'folio_ref' => 'int',
'razon_re' => 'string',
'nro_lin_ref' => 'int',
'tpo_doc_ref' => 'int'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'fch_ref' => null,
'folio_ref' => null,
'razon_re' => null,
'nro_lin_ref' => null,
'tpo_doc_ref' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fch_ref' => 'FchRef',
'folio_ref' => 'FolioRef',
'razon_re' => 'RazonRe',
'nro_lin_ref' => 'NroLinRef',
'tpo_doc_ref' => 'TpoDocRef'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fch_ref' => 'setFchRef',
'folio_ref' => 'setFolioRef',
'razon_re' => 'setRazonRe',
'nro_lin_ref' => 'setNroLinRef',
'tpo_doc_ref' => 'setTpoDocRef'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fch_ref' => 'getFchRef',
'folio_ref' => 'getFolioRef',
'razon_re' => 'getRazonRe',
'nro_lin_ref' => 'getNroLinRef',
'tpo_doc_ref' => 'getTpoDocRef'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['fch_ref'] = isset($data['fch_ref']) ? $data['fch_ref'] : null;
        $this->container['folio_ref'] = isset($data['folio_ref']) ? $data['folio_ref'] : null;
        $this->container['razon_re'] = isset($data['razon_re']) ? $data['razon_re'] : null;
        $this->container['nro_lin_ref'] = isset($data['nro_lin_ref']) ? $data['nro_lin_ref'] : null;
        $this->container['tpo_doc_ref'] = isset($data['tpo_doc_ref']) ? $data['tpo_doc_ref'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fch_ref
     *
     * @return string
     */
    public function getFchRef()
    {
        return $this->container['fch_ref'];
    }

    /**
     * Sets fch_ref
     *
     * @param string $fch_ref fch_ref
     *
     * @return $this
     */
    public function setFchRef($fch_ref)
    {
        $this->container['fch_ref'] = $fch_ref;

        return $this;
    }

    /**
     * Gets folio_ref
     *
     * @return int
     */
    public function getFolioRef()
    {
        return $this->container['folio_ref'];
    }

    /**
     * Sets folio_ref
     *
     * @param int $folio_ref folio_ref
     *
     * @return $this
     */
    public function setFolioRef($folio_ref)
    {
        $this->container['folio_ref'] = $folio_ref;

        return $this;
    }

    /**
     * Gets razon_re
     *
     * @return string
     */
    public function getRazonRe()
    {
        return $this->container['razon_re'];
    }

    /**
     * Sets razon_re
     *
     * @param string $razon_re razon_re
     *
     * @return $this
     */
    public function setRazonRe($razon_re)
    {
        $this->container['razon_re'] = $razon_re;

        return $this;
    }

    /**
     * Gets nro_lin_ref
     *
     * @return int
     */
    public function getNroLinRef()
    {
        return $this->container['nro_lin_ref'];
    }

    /**
     * Sets nro_lin_ref
     *
     * @param int $nro_lin_ref nro_lin_ref
     *
     * @return $this
     */
    public function setNroLinRef($nro_lin_ref)
    {
        $this->container['nro_lin_ref'] = $nro_lin_ref;

        return $this;
    }

    /**
     * Gets tpo_doc_ref
     *
     * @return int
     */
    public function getTpoDocRef()
    {
        return $this->container['tpo_doc_ref'];
    }

    /**
     * Sets tpo_doc_ref
     *
     * @param int $tpo_doc_ref tpo_doc_ref
     *
     * @return $this
     */
    public function setTpoDocRef($tpo_doc_ref)
    {
        $this->container['tpo_doc_ref'] = $tpo_doc_ref;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
