<?php
/**
 * DTEReceptor
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * DTEReceptor Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DTEReceptor implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DTEReceptor';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'rut_recep' => 'string',
'rzn_soc_recep' => 'string',
'giro_recep' => 'string',
'dir_recep' => 'string',
'cmna_recep' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'rut_recep' => null,
'rzn_soc_recep' => null,
'giro_recep' => null,
'dir_recep' => null,
'cmna_recep' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'rut_recep' => 'RUTRecep',
'rzn_soc_recep' => 'RznSocRecep',
'giro_recep' => 'GiroRecep',
'dir_recep' => 'DirRecep',
'cmna_recep' => 'CmnaRecep'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'rut_recep' => 'setRutRecep',
'rzn_soc_recep' => 'setRznSocRecep',
'giro_recep' => 'setGiroRecep',
'dir_recep' => 'setDirRecep',
'cmna_recep' => 'setCmnaRecep'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'rut_recep' => 'getRutRecep',
'rzn_soc_recep' => 'getRznSocRecep',
'giro_recep' => 'getGiroRecep',
'dir_recep' => 'getDirRecep',
'cmna_recep' => 'getCmnaRecep'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['rut_recep'] = isset($data['rut_recep']) ? $data['rut_recep'] : null;
        $this->container['rzn_soc_recep'] = isset($data['rzn_soc_recep']) ? $data['rzn_soc_recep'] : null;
        $this->container['giro_recep'] = isset($data['giro_recep']) ? $data['giro_recep'] : null;
        $this->container['dir_recep'] = isset($data['dir_recep']) ? $data['dir_recep'] : null;
        $this->container['cmna_recep'] = isset($data['cmna_recep']) ? $data['cmna_recep'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets rut_recep
     *
     * @return string
     */
    public function getRutRecep()
    {
        return $this->container['rut_recep'];
    }

    /**
     * Sets rut_recep
     *
     * @param string $rut_recep rut_recep
     *
     * @return $this
     */
    public function setRutRecep($rut_recep)
    {
        $this->container['rut_recep'] = $rut_recep;

        return $this;
    }

    /**
     * Gets rzn_soc_recep
     *
     * @return string
     */
    public function getRznSocRecep()
    {
        return $this->container['rzn_soc_recep'];
    }

    /**
     * Sets rzn_soc_recep
     *
     * @param string $rzn_soc_recep rzn_soc_recep
     *
     * @return $this
     */
    public function setRznSocRecep($rzn_soc_recep)
    {
        $this->container['rzn_soc_recep'] = $rzn_soc_recep;

        return $this;
    }

    /**
     * Gets giro_recep
     *
     * @return string
     */
    public function getGiroRecep()
    {
        return $this->container['giro_recep'];
    }

    /**
     * Sets giro_recep
     *
     * @param string $giro_recep giro_recep
     *
     * @return $this
     */
    public function setGiroRecep($giro_recep)
    {
        $this->container['giro_recep'] = $giro_recep;

        return $this;
    }

    /**
     * Gets dir_recep
     *
     * @return string
     */
    public function getDirRecep()
    {
        return $this->container['dir_recep'];
    }

    /**
     * Sets dir_recep
     *
     * @param string $dir_recep dir_recep
     *
     * @return $this
     */
    public function setDirRecep($dir_recep)
    {
        $this->container['dir_recep'] = $dir_recep;

        return $this;
    }

    /**
     * Gets cmna_recep
     *
     * @return string
     */
    public function getCmnaRecep()
    {
        return $this->container['cmna_recep'];
    }

    /**
     * Sets cmna_recep
     *
     * @param string $cmna_recep cmna_recep
     *
     * @return $this
     */
    public function setCmnaRecep($cmna_recep)
    {
        $this->container['cmna_recep'] = $cmna_recep;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
