<?php
/**
 * DocumentReceivedItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DocumentReceivedItemsTest Class Doc Comment
 *
 * @category    Class
 * @description DocumentReceivedItems
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentReceivedItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocumentReceivedItems"
     */
    public function testDocumentReceivedItems()
    {
    }

    /**
     * Test attribute "rut_emisor"
     */
    public function testPropertyRutEmisor()
    {
    }

    /**
     * Test attribute "dv"
     */
    public function testPropertyDv()
    {
    }

    /**
     * Test attribute "rzn_soc"
     */
    public function testPropertyRznSoc()
    {
    }

    /**
     * Test attribute "tipo_dte"
     */
    public function testPropertyTipoDte()
    {
    }

    /**
     * Test attribute "folio"
     */
    public function testPropertyFolio()
    {
    }

    /**
     * Test attribute "fch_emis"
     */
    public function testPropertyFchEmis()
    {
    }

    /**
     * Test attribute "mnt_exe"
     */
    public function testPropertyMntExe()
    {
    }

    /**
     * Test attribute "mnt_neto"
     */
    public function testPropertyMntNeto()
    {
    }

    /**
     * Test attribute "iva"
     */
    public function testPropertyIva()
    {
    }

    /**
     * Test attribute "mnt_total"
     */
    public function testPropertyMntTotal()
    {
    }

    /**
     * Test attribute "acuses"
     */
    public function testPropertyAcuses()
    {
    }

    /**
     * Test attribute "fma_pago"
     */
    public function testPropertyFmaPago()
    {
    }

    /**
     * Test attribute "tpo_tran_compra"
     */
    public function testPropertyTpoTranCompra()
    {
    }
}
