<?php
/**
 * DTEDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DTEDetailTest Class Doc Comment
 *
 * @category    Class
 * @description DTEDetail
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DTEDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DTEDetail"
     */
    public function testDTEDetail()
    {
    }

    /**
     * Test attribute "nro_lin_det"
     */
    public function testPropertyNroLinDet()
    {
    }

    /**
     * Test attribute "nmb_item"
     */
    public function testPropertyNmbItem()
    {
    }

    /**
     * Test attribute "qty_item"
     */
    public function testPropertyQtyItem()
    {
    }

    /**
     * Test attribute "prc_item"
     */
    public function testPropertyPrcItem()
    {
    }

    /**
     * Test attribute "monto_item"
     */
    public function testPropertyMontoItem()
    {
    }
}
