<?php
/**
 * DTEEmisorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DTEEmisorTest Class Doc Comment
 *
 * @category    Class
 * @description DTEEmisor
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DTEEmisorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DTEEmisor"
     */
    public function testDTEEmisor()
    {
    }

    /**
     * Test attribute "rut_emisor"
     */
    public function testPropertyRutEmisor()
    {
    }

    /**
     * Test attribute "rzn_soc"
     */
    public function testPropertyRznSoc()
    {
    }

    /**
     * Test attribute "giro_emis"
     */
    public function testPropertyGiroEmis()
    {
    }

    /**
     * Test attribute "acteco"
     */
    public function testPropertyActeco()
    {
    }

    /**
     * Test attribute "dir_origen"
     */
    public function testPropertyDirOrigen()
    {
    }

    /**
     * Test attribute "cmna_origen"
     */
    public function testPropertyCmnaOrigen()
    {
    }

    /**
     * Test attribute "telefono"
     */
    public function testPropertyTelefono()
    {
    }

    /**
     * Test attribute "cdg_sii_sucur"
     */
    public function testPropertyCdgSiiSucur()
    {
    }
}
