<?php
/**
 * DTEIdDocTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DTEIdDocTest Class Doc Comment
 *
 * @category    Class
 * @description DTEIdDoc
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DTEIdDocTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DTEIdDoc"
     */
    public function testDTEIdDoc()
    {
    }

    /**
     * Test attribute "tipo_dte"
     */
    public function testPropertyTipoDte()
    {
    }

    /**
     * Test attribute "folio"
     */
    public function testPropertyFolio()
    {
    }

    /**
     * Test attribute "fch_emis"
     */
    public function testPropertyFchEmis()
    {
    }

    /**
     * Test attribute "tpo_tran_compra"
     */
    public function testPropertyTpoTranCompra()
    {
    }

    /**
     * Test attribute "tpo_tran_venta"
     */
    public function testPropertyTpoTranVenta()
    {
    }

    /**
     * Test attribute "fma_pago"
     */
    public function testPropertyFmaPago()
    {
    }
}
