<?php
/**
 * DTEReferenciaItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tsukiro\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tsukiro\Client;

/**
 * DTEReferenciaItemTest Class Doc Comment
 *
 * @category    Class
 * @description DTEReferenciaItem
 * @package     Tsukiro\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DTEReferenciaItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DTEReferenciaItem"
     */
    public function testDTEReferenciaItem()
    {
    }

    /**
     * Test attribute "fch_ref"
     */
    public function testPropertyFchRef()
    {
    }

    /**
     * Test attribute "folio_ref"
     */
    public function testPropertyFolioRef()
    {
    }

    /**
     * Test attribute "razon_re"
     */
    public function testPropertyRazonRe()
    {
    }

    /**
     * Test attribute "nro_lin_ref"
     */
    public function testPropertyNroLinRef()
    {
    }

    /**
     * Test attribute "tpo_doc_ref"
     */
    public function testPropertyTpoDocRef()
    {
    }
}
