<?php
/**
 * DTEReceptorTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tsukiro\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tsukiro\Client;

/**
 * DTEReceptorTest Class Doc Comment
 *
 * @category    Class
 * @description DTEReceptor
 * @package     Tsukiro\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DTEReceptorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DTEReceptor"
     */
    public function testDTEReceptor()
    {
    }

    /**
     * Test attribute "rut_recep"
     */
    public function testPropertyRutRecep()
    {
    }

    /**
     * Test attribute "rzn_soc_recep"
     */
    public function testPropertyRznSocRecep()
    {
    }

    /**
     * Test attribute "giro_recep"
     */
    public function testPropertyGiroRecep()
    {
    }

    /**
     * Test attribute "dir_recep"
     */
    public function testPropertyDirRecep()
    {
    }

    /**
     * Test attribute "cmna_recep"
     */
    public function testPropertyCmnaRecep()
    {
    }
}
