<?php
/**
 * DTEResponseRESOLUCIONTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tsukiro\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tsukiro\Client;

/**
 * DTEResponseRESOLUCIONTest Class Doc Comment
 *
 * @category    Class
 * @description DTEResponseRESOLUCION
 * @package     Tsukiro\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DTEResponseRESOLUCIONTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DTEResponseRESOLUCION"
     */
    public function testDTEResponseRESOLUCION()
    {
    }

    /**
     * Test attribute "fecha"
     */
    public function testPropertyFecha()
    {
    }

    /**
     * Test attribute "numero"
     */
    public function testPropertyNumero()
    {
    }
}
