<?php
/**
 * DTERequestDteEncabezadoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DTERequestDteEncabezadoTest Class Doc Comment
 *
 * @category    Class
 * @description DTERequestDteEncabezado
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DTERequestDteEncabezadoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DTERequestDteEncabezado"
     */
    public function testDTERequestDteEncabezado()
    {
    }

    /**
     * Test attribute "id_doc"
     */
    public function testPropertyIdDoc()
    {
    }

    /**
     * Test attribute "emisor"
     */
    public function testPropertyEmisor()
    {
    }

    /**
     * Test attribute "receptor"
     */
    public function testPropertyReceptor()
    {
    }

    /**
     * Test attribute "totales"
     */
    public function testPropertyTotales()
    {
    }
}
