<?php
/**
 * DTETotalesTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tsukiro\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * OpenFactura API
 *
 * Estructura de openfactura
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.27
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tsukiro\Client;

/**
 * DTETotalesTest Class Doc Comment
 *
 * @category    Class
 * @description DTETotales
 * @package     Tsukiro\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DTETotalesTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DTETotales"
     */
    public function testDTETotales()
    {
    }

    /**
     * Test attribute "mnt_neto"
     */
    public function testPropertyMntNeto()
    {
    }

    /**
     * Test attribute "tasa_iva"
     */
    public function testPropertyTasaIva()
    {
    }

    /**
     * Test attribute "iva"
     */
    public function testPropertyIva()
    {
    }

    /**
     * Test attribute "mnt_total"
     */
    public function testPropertyMntTotal()
    {
    }

    /**
     * Test attribute "monto_periodo"
     */
    public function testPropertyMontoPeriodo()
    {
    }

    /**
     * Test attribute "vlr_pagar"
     */
    public function testPropertyVlrPagar()
    {
    }
}
